[build]
  functions = "netlify/functions"
  publish = "public"
  command = "echo 'Build complete - Static site with Python functions'"

# Chỉ định environment variables nếu cần
[build.environment]
  NODE_VERSION = "18"

# XÓA HOÀN TOÀN phần plugins - không cần disable Next.js plugin

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/api/:splat"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
