[build]
  functions = "netlify/functions"
  publish = "public"
  command = "echo 'Static HTML site ready'"

[build.environment]
  NETLIFY_NEXT_PLUGIN_SKIP = "true"
  DISABLE_NEXT_PLUGIN = "true"

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/api/:splat"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
