[build]
  functions = "netlify/functions"
  publish = "public"             # Đã thay đổi để chỉ định thư mục xuất bản

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/api/:splat"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
